name: cli checks
on:
  pull_request:
    branches:
      - "master"
    paths:
      - "clients/cli/**.cc"
      - ".github/workflows/cli.yml"
jobs:
  cli_unit_tests:
    steps:
      - uses: actions/checkout@v2
      - name: run unit tests
        run: echo "should run static analysis here"
