name: docs checks
on:
  pull_request:
    branches:
      - "master"
    paths:
      - "docs/**.md"
      - ".github/workflows/docs.yml"
jobs:
  markdown_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run unit tests
        run: echo "should run markdown lint here"
  github_pages_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run unit tests
        run: echo "should run build test here"
